Slightly better command-line processing in unmp

diff --git a/unmp b/unmp
--- a/unmp
+++ b/unmp
@@ -14,26 +14,29 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-while getopts "hfdrv" OPT; do
+while getopts ":hfdrv" OPT; do
 	case "$OPT" in
 		h) help=1 ;;
 		f) force=1 ;;
 		d) delete=1 ;;
 		r) rename=1 ;;
 		v) verbose=1 ;;
+		?) echo "Invalid option '$OPTARG'" 1>&2; help=1 ;;
 	esac
 done
 shift $((OPTIND - 1))
 
 if [[ $help ]]; then
-	echo "Usage: $0 [-h] [-f] [-d] [-r] [-v] dir..." 1>&2
-	echo "Removes the video component from the Android \"Motion Photo\" files in the given directories" 1>&2
+	echo "Usage: $0 [-h] [-f] [-d] [-r] [-v] [--] dir..." 1>&2
 	echo -e "\t-h\tShow help and exit" 1>&2
 	echo -e "\t-f\tOverwrite existing files" 1>&2
 	echo -e "\t-d\tDelete source files on success" 1>&2
 	echo -e "\t-r\tJust rename files that don't actually contain video" 1>&2
 	echo -e "\t-v\tBe verbose, list processed files" 1>&2
+	echo -e "\t--\tOptional separator for directory names starting with '-'" 1>&2
 	echo -e "\tdir...\tDirectories to process" 1>&2
+	echo "Removes the video component from the Android \"Motion Photo\" files in the given directories" 1>&2
+	echo "The result of cleaning the file x.MP.jpg is saved to the file x.jpg" 1>&2
 	exit 0
 fi
 
@@ -53,7 +56,7 @@ while [[ "$1" ]]; do
 			echo "Skipping '$src': not a regular file" 1>&2
 			continue
 		fi
-		dst=${src/.MP/}
+		dst=${src/.MP./.}
 		if [[ -e $dst ]] && [[ ! $force ]]; then
 			echo "Skipping '$src': target exists" 1>&2
 			continue
